### ISSUE TITLE
"Errors in currently selected datapacks prevented world from loading"

### ISSUE THREAD

**Issue by Freebi85** [JDKDigital/productive-bees#122]
Hey There 👋 

MC Version 1.16.4
Forge: 35.1.13
ProductiveBees:1.16.3-0.5.1.1.

After loading a world with productive bees, it's not possible anymore to load or create other worlds without restarting the client entirely.

This is the issue when trying to load new or existing worlds after the first one:
_Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually. ... You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually._

ProductiveBees Version 1.16.3-0.5.0.5 works still fine but it was removed from curse. Now it's not possible to upload packs anymore without removing the mod compeltely. Maybe it would be possible to enable the old version again for the time beeing.

This is my log right after the issue.
[latest.log](https://github.com/JDKDigital/productive-bees/files/5721081/latest.log)

Lots of _java.lang.IllegalStateException: Duplicate key net.minecraft.tags_ not sure is this is helpfull at all.

Cheers 🍺

**Comment by JaisDK** [comment]
That's a weird error, I will look into it later. I've enabled the 0.5.0.5 version for now.

Do you have any actual datapacks enabled?

**Comment by Freebi85** [comment]
Thank you very much :)
Yes but not for ProductiveBees. And mostly just advancemenrt stuff.

**Comment by JaisDK** [comment]
Could I get your debug log as well?

**Comment by Freebi85** [comment]
Ah Yes of Course.
[debug-2.log](https://github.com/JDKDigital/productive-bees/files/5721132/debug-2.log)

**Comment by JaisDK** [comment]
It looks like it's from a different run, it does not have the error that the latest.log had.

**Comment by Freebi85** [comment]
ah my bad sorry :/

[debug-4.log](https://github.com/JDKDigital/productive-bees/files/5721274/debug-4.log)

**Comment by JaisDK** [comment]
With just my mod I am unable to recreate the problem. I did have a similar error when I had a datapack enabled. Can you send me the datapack you are using or see if you still have a problem without the datapack?

**Comment by JaisDK** [comment]
I think I fixed it in the newest version, please verify when you have the time :)

**Comment by Freebi85** [comment]
Alright i removed all datapacks and tried again in latest version but it still happens :/
[latest.log](https://github.com/JDKDigital/productive-bees/files/5734313/latest.log)
[debug.log](https://github.com/JDKDigital/productive-bees/files/5734314/debug.log)

Might be mod interaction or something hm

**Comment by JaisDK** [comment]
Also with the new version?

**Comment by Freebi85** [comment]
Yes :/

**Comment by JaisDK** [comment]
I think I can force the error if I make a mistake in one of the bee config, but we must be running different Java runtime environments, because I get a much better error message than you.

```
Caused by: java.lang.IllegalStateException: Duplicate key thermal:niter_block (attempted merging values net.minecraft.tags.Tag@3de229fb and net.minecraft.tags.Tag@582d797c)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133) ~[?:?] {}
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?] {}
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] {}
	at net.minecraft.tags.TagRegistry.reinjectOptionalTags(TagRegistry.java:89) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraft.tags.ITagCollectionSupplier.reinjectOptionalTags(ITagCollectionSupplier.java:65) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:49) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.lambda$new$3(AsyncReloader.java:66) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:139) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:122) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.reloadDatapacks(Minecraft.java:1905) ~[forge-1.16.4-35.1.11_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 32 more
```

It's a lot to ask, but could you switch to the "normal" JRE and see if you get a more descriptive error message?

**Comment by JaisDK** [comment]
So it turns out, I am using OpenJDK which means you are probably using the "normal" one :)

**Comment by JaisDK** [comment]
Maybe you could zip your mod folder and send it to me?

**Comment by Freebi85** [comment]
It's probably easier for you just downloading latest files from curse^^
https://www.curseforge.com/minecraft/modpacks/explorico-1-16-4/files/3145324

will try with openjdk 👍

**Comment by JaisDK** [comment]
I am unable to recreate this using version 1.4a of Explorico

**Comment by ColdFang** [comment]
I am getting the same error in my own modpack. I tried to narrow it down with a small test setup. I think its happening with different mods. It wasnt any mod from the Explorico Pack for me but Eidolon together with JEI. 

Im very confused, just look at this overview I made :D

Forge Version: 35.1.15



![Testges](https://user-images.githubusercontent.com/13708113/103168390-27036d00-4833-11eb-9003-163e1d6186bc.png)

Hope this helps in some way

**Comment by Febilian** [comment]
It's definitely not just one mod interaction here - I was able to trigger this error with nothing but Ice and Fire(and its dependency Citadel) installed along JEI and Productive Bees in a test instance. Removing Productive Bees makes the error stop.

Hopefully this will help narrow down what the common factor is.


Contents of mods folder(configs are not edited):
![installed_mods](https://user-images.githubusercontent.com/13922447/103168866-efbd9d80-47eb-11eb-8329-d1a989c87ac3.png)

[latest.log](https://github.com/JDKDigital/productive-bees/files/5744413/latest.log)

**Comment by JaisDK** [comment]
Thank you both, this will definitely help narrow it down.

**Comment by JaisDK** [comment]
[productivebees-1.16.4-0.5.2.2.zip](https://github.com/JDKDigital/productive-bees/files/5748621/productivebees-1.16.4-0.5.2.2.zip)

Could you try this version of the mod and see if the problem is resolved?

**Comment by ColdFang** [comment]
Nope. 
Test was with same setup (PB + JEI + Eidolon)
With this version I cant even load a singleplayer world.
When trying to load the world, after its reaching 100% this shows up: 

![Screenshot_6](https://user-images.githubusercontent.com/13708113/103243659-d9821f80-495a-11eb-8a11-ce94d84a51f0.png)

The game throws me back in the multiplayer menu after that. 
If you try to create a new world after that it gives the same " Errors in currently selected datapacks"  error from before.
Same procedure after a game restart.

**Comment by JaisDK** [comment]
[productivebees-1.16.4-0.5.2.2.zip](https://github.com/JDKDigital/productive-bees/files/5749242/productivebees-1.16.4-0.5.2.2.zip)

Turns out Ice&Fire add copper and silver blocks without adding them to the storage_blocks block tag, only the item tag.
Eidolon adds sulfur without having a sulfur block, which is fine, I just hadn't expected a mod to not have the block.
Both have been addressed in the linked version.

**Comment by JaisDK** [comment]
If the new version does not fix the problem for you, let me know.

**Comment by drakray** [comment]
Hi there, for me this is still not working with PB 0.5.2.5, I&F 2.1.4 and a buncha other, however, removing I&F allow me to try to start another world, without the "errors in currently selected datapack", but the loading just seems to fail after FOREVER without info even in the log... :/
Really seems like a big interaction mess :(

**Comment by JaisDK** [comment]
Latest version, 0.5.2.6, has some changes to the bee config so it will hopefully disable whatever bee is causing trouble with I&F. I don't know if the other problem is related. If it still happens can you post your debug log?

**Comment by papaworld** [comment]
Hi Ya, I've been running 1.16.4 for a while... got the typical "datapack" world load error. Running through the 200+ mods installed there were some interfering with Productive Bees as it seems. After removing 3 of these "minor" mods, I was still getting the load error... I gave up because it is so time consuming and lack of "true" error reporting. What ever ya'll did to Productive Bees 1.16.5 0.5.2.11 totally fixed it all up in the 1.16.4 world and re-installed those other "minor" mods. Thank you, very much appreciated.

**Comment by JaisDK** [comment]
The last mod to cause problems was Ex Nihilo, got that fixed in .10 and .11 :)

**Comment by butterminecart** [comment]
Hi I am also having a problem with my own mod about this error minecraft now loads my mod without an error I need help I need to finish this mod update by October 24th if you want me to send you a file let me know.

**Comment by JaisDK** [comment]
Please don't post to a closed issue.

If you have an issue with my mod, open a new issue. For modding help, go to one of the modding Discord servers.

**Comment by butterminecart** [comment]
its not your mod its my mod

**Comment by JaisDK** [comment]
a closed issue on the issue tracker is not the place for that, you are welcome to come to my discord if you want, I don't mind helping out with other mods when I have the time

**Comment by beta292** [comment]
i removel all the mods and the problem stay the same. What i need to do?

**Comment by JaisDK** [comment]
Open a new issue and provide a log
