### ISSUE TITLE
[1.16.5] Skipping Entity with id spam caused by Advanced Beehive

### ISSUE THREAD

**Issue by shortybsd** [JDKDigital/productive-bees#169]
Forge Version: 36.0.55
Productive Bees Version: 0.6.9.4

I have an advanced hive that if you place down it will spam server console the following:
`[15Mar2021 01:13:53.403] [Server thread/WARN] [net.minecraft.entity.EntityType/]: Skipping Entity with id `

Note: No entity is specified. My log file is over 200mb from this constantly spamming. It spams this 20 times per second.
I had the area for my beehives chunkloaded before I went to bed. Woke up to server constantly spamming this. I unloaded the chunkloaded area, went to spawn and the spam stopped. I went back to base (spam started) so I broke up each of the advanced hives then spam stopped once more.

This is the beehive in question, causing all the spam. I couldn't capture the entire NBT tags, scrolled off the screen.

![advanced_beehive_spam](https://user-images.githubusercontent.com/7765399/111112946-0348ec80-852f-11eb-827b-5144f591446d.png)

It is specifically the ZomBee causing all this chaos. They are invisible. All other beehives with any bee except for the ZomBee do not create the spam. Also, I do not have any clue how I had all my bees transfer into zombee's, they were mostly vanilla. That same bugged hive changed over to all ZomBee's same for my other hives.

Update: Keeping mod. To anyone with same issue, update your server's config to the following until mod author fixes this mod:
Server config location: YourServer\YourWorldName\serverconfig\productivebees-server.toml
Under that file change the boolean value from true to false:
 `spawnUndeadBees = false`

**Comment by shortybsd** [comment]
Fixed in 0.6.9.5. 
"0.6.9.5
-- Fixed game events not firing causing invisible bees and other issues"

**Comment by Eidigii** [comment]
This issue still persists in later version (currently on 0.6.9.9). For example this hive:
![image](https://user-images.githubusercontent.com/2285548/116190700-cb3ee700-a733-11eb-82bd-54b10a4c0921.png)
When it is placed in the world I get the endless spam in server:
![image](https://user-images.githubusercontent.com/2285548/116190737-d8f46c80-a733-11eb-99cf-55d69b80ac26.png)
It actually has 3 crystalline bees in it
