### ISSUE TITLE
[1.15.2] crash in common_setup event phase

### ISSUE THREAD

**Issue by jarquafelmu** [JDKDigital/productive-bees#53]
Crash when loading server

https://gist.github.com/jarquafelmu/8cf207caad0cfc36cae2f5cdfb8abdb8

**Comment by JaisDK** [comment]
Can you post the full log from the server?

**Comment by jarquafelmu** [comment]
[2020-07-25-1.log.gz](https://github.com/JDKDigital/productive-bees/files/4976756/2020-07-25-1.log.gz)

**Comment by JaisDK** [comment]
Thanks.

There's not really anything that stands out as the culprit. Does this happen on the server side or the client and does it happen when the server start or when you try to connect?

**Comment by JaisDK** [comment]
The correct error is in the log, just a little further up. The code it' complaining about however is also running inside Abnormals Core, does everything work fine if you remove productive bees?

```
[25Jul2020 18:56:41.506] [modloading-worker-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2725/160038536@4af3539e
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218)
	at cy.jdkdigital.productivebees.ProductiveBees.lambda$null$5(ProductiveBees.java:153)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at cy.jdkdigital.productivebees.ProductiveBees.lambda$fixPOI$6(ProductiveBees.java:151)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at cy.jdkdigital.productivebees.ProductiveBees.fixPOI(ProductiveBees.java:150)
	at cy.jdkdigital.productivebees.ProductiveBees.preInit(ProductiveBees.java:85)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jarquafelmu** [comment]
everything works fine without productive bees, this happens at server start according to my friend who is the server owner it's intermittent and sometimes works and sometimes not but now it's just not

**Comment by JaisDK** [comment]
It must a concurrency issue where part of the fixPOI method is run in a different thread which would explain why it works sometimes. I've attached a new version where I've tried to limit the multi-threading, could you try it out and see if it solves the issue? Unfortunately I can't test it myself as I can't reproduce the problem on my system.

**Comment by JaisDK** [comment]
[productivebees-1.15.2-0.1.16b.zip](https://github.com/JDKDigital/productive-bees/files/4976954/productivebees-1.15.2-0.1.16b.zip)

**Comment by JaisDK** [comment]
excuse the spoilers ;)

**Comment by jarquafelmu** [comment]
thanks

**Comment by jarquafelmu** [comment]
The server crashes on the next reboot after placing hives down.

this crash happened with  the 0.1.16b
[latest_1.log](https://github.com/JDKDigital/productive-bees/files/4976992/latest_1.log)
[crash-2020-07-26_01.07.30-server.txt](https://github.com/JDKDigital/productive-bees/files/4976993/crash-2020-07-26_01.07.30-server.txt)

**Comment by JaisDK** [comment]
did the server load up the first time? It seems like nothing was resolved. I don't think the placing of hives matters. 

I'll give it one more shot before going to bed. This version should at least not crash, but bees might not be able to find the hives.
If there are problems you will see something like this in the log "Could not add blockstate to beehive POI ..."

[productivebees-1.15.2-0.1.16c.zip](https://github.com/JDKDigital/productive-bees/files/4977011/productivebees-1.15.2-0.1.16c.zip)

**Comment by nanonestor** [comment]
Hi - I'm the one with the above server. Yes the first beta file posted here did load first time, on restarts it failed/crashed with the last posted log/crash files (tried restarting several times). Upon removing the mod and restarting it worked first time.

**Comment by nanonestor** [comment]
That worked!  I've rebooted at least half a dozen times and it loads with no crashing every time now.  I'm still not clear on how the new bee system works (why I included bees onto the modpack in the first place).  fwiw I shift-right clicked a slime bee in cage on an advanced hive (maybe that does nothing besides releasing bee in proximity? have no idea yet), it did go inside the hive and produced slime combs.

**Comment by JaisDK** [comment]
Nice pack, I'll get the fix out in a new version soon so you can add it. Did you notice anything in the server log saying "Could not add blockstate to beehive POI ..."?

Shift clicking on the hive will just release it, but if it's night or the bees has nectar, then it will go in immediately.

**Comment by nanonestor** [comment]
No errors about blockstate :)

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3016467

**Comment by jarquafelmu** [comment]
That's a broken link
